![title](imagens/cabec_08g.jpg)

## <font color='green'>Projeto 6 - Marketing para Instituições Financeiras - Parte 02</font>
## <font color='green'>Realizando a Análise Exploratória dos Dados</font>

## Carregando os Pacotes e os Dados

In [1]:
# Importação dos Pacotes necessários para este projeto
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "pyPRO - Seja um Profissional Python!" --iversions

Author: pyPRO - Seja um Profissional Python!

pandas    : 2.2.2
numpy     : 1.26.4
matplotlib: 3.8.4
seaborn   : 0.13.2

In [3]:
# Carrega o dataset
df = pd.read_csv("dados/bank-full.csv")

In [4]:
# Shape
df.shape

(45211, 18)

In [5]:
# Amostra
df.head()

,id,age,job,maritalEdu,salary,balance,default,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target
0,1,58.0,management,married-tertiary,100000.0,2143,no,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,2,44.0,technician,single-secondary,60000.0,29,no,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,3,33.0,entrepreneur,married-secondary,120000.0,2,no,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,4,47.0,blue-collar,married-unknown,20000.0,1506,no,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,5,33.0,unknown,single-unknown,0.0,1,no,no,no,unknown,5,may,198,1,-1,0,unknown,no

## Análise Exploratória

In [6]:
# Info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          45211 non-null  int64
 1   age         45190 non-null  float64
 2   job         45211 non-null  object
 3   maritalEdu  45211 non-null  object
 4   salary      45180 non-null  float64
 5   balance     45211 non-null  int64
 6   default     45211 non-null  object
 7   housing     45211 non-null  object
 8   loan        45211 non-null  object
 9   contact     45211 non-null  object
 10  day         45211 non-null  int64
 11  month       45188 non-null  object
 12  duration    45211 non-null  int64
 13  campaign    45211 non-null  int64
 14  pdays       45211 non-null  int64
 15  previous    45211 non-null  int64
 16  poutcome    45211 non-null  object
 17  target      45204 non-null  object
dtypes: float64(2), int64(7), object(9)
memory usage: 6.2+ MB

In [7]:
# Temos valores nulos?
df.isna().any()

id            False
age            True
job           False
maritalEdu    False
salary         True
balance       False
default       False
housing       False
loan          False
contact       False
day           False
month          True
duration      False
campaign      False
pdays         False
previous      False
poutcome      False
target         True
dtype: bool

In [8]:
# Temos valores nulos?
df.isna().sum()

id             0
age           21
job            0
maritalEdu     0
salary        31
balance        0
default        0
housing        0
loan           0
contact        0
day            0
month         23
duration       0
campaign       0
pdays          0
previous       0
poutcome       0
target         7
dtype: int64

In [9]:
# Não usaremos a coluna ID. Portanto, vamos removê-la.
df.drop(["id"], axis = 1, inplace = True)

In [10]:
# Colunas
df.columns

Index(['age', 'job', 'maritalEdu', 'salary', 'balance', 'default', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'target'],
      dtype='object')

## Corrigindo a coluna "maritalEdu" 
Esta coluna apresenta duas informações: Estado Civil (marital) e Nivel Educacional (education). 
Vamos separar em duas colunas distintas.

In [11]:
df.head()

,age,job,maritalEdu,salary,balance,default,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target
0,58.0,management,married-tertiary,100000.0,2143,no,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44.0,technician,single-secondary,60000.0,29,no,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33.0,entrepreneur,married-secondary,120000.0,2,no,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47.0,blue-collar,married-unknown,20000.0,1506,no,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33.0,unknown,single-unknown,0.0,1,no,no,no,unknown,5,may,198,1,-1,0,unknown,no

In [12]:
# Vamos fazer o split da coluna "maritalEdu" e criarmos a coluna "marital" com o primeiro elemento antes do hífen (-)
df['marital'] = df["maritalEdu"].apply(lambda x:x.split("-")[0])

In [13]:
df.head()

,age,job,maritalEdu,salary,balance,default,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target,marital
0,58.0,management,married-tertiary,100000.0,2143,no,yes,no,unknown,5,may,261,1,-1,0,unknown,no,married
1,44.0,technician,single-secondary,60000.0,29,no,yes,no,unknown,5,may,151,1,-1,0,unknown,no,single
2,33.0,entrepreneur,married-secondary,120000.0,2,no,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,married
3,47.0,blue-collar,married-unknown,20000.0,1506,no,yes,no,unknown,5,may,92,1,-1,0,unknown,no,married
4,33.0,unknown,single-unknown,0.0,1,no,no,no,unknown,5,may,198,1,-1,0,unknown,no,single

In [14]:
# Vamos fazer o split da coluna "maritalEdu" e criarmos a coluna "education" com o segundo elemento antes do hífen (-)
df['education'] = df["maritalEdu"].apply(lambda x:x.split("-")[1])

In [15]:
df.head()

,age,job,maritalEdu,salary,balance,default,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target,marital,education
0,58.0,management,married-tertiary,100000.0,2143,no,yes,no,unknown,5,may,261,1,-1,0,unknown,no,married,tertiary
1,44.0,technician,single-secondary,60000.0,29,no,yes,no,unknown,5,may,151,1,-1,0,unknown,no,single,secondary
2,33.0,entrepreneur,married-secondary,120000.0,2,no,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,married,secondary
3,47.0,blue-collar,married-unknown,20000.0,1506,no,yes,no,unknown,5,may,92,1,-1,0,unknown,no,married,unknown
4,33.0,unknown,single-unknown,0.0,1,no,no,no,unknown,5,may,198,1,-1,0,unknown,no,single,unknown

In [16]:
# Drop da coluna "jobedu" 
df.drop(["maritalEdu"], axis = 1, inplace = True)

In [17]:
df.head()

,age,job,salary,balance,default,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,target,marital,education
0,58.0,management,100000.0,2143,no,yes,no,unknown,5,may,261,1,-1,0,unknown,no,married,tertiary
1,44.0,technician,60000.0,29,no,yes,no,unknown,5,may,151,1,-1,0,unknown,no,single,secondary
2,33.0,entrepreneur,120000.0,2,no,yes,yes,unknown,5,may,76,1,-1,0,unknown,no,married,secondary
3,47.0,blue-collar,20000.0,1506,no,yes,no,unknown,5,may,92,1,-1,0,unknown,no,married,unknown
4,33.0,unknown,0.0,1,no,no,no,unknown,5,may,198,1,-1,0,unknown,no,single,unknown

In [18]:
df.shape

(45211, 18)

## Salvando os Dados desta Etapa 2

In [19]:
# Salvando os dados
df.to_csv('dados/bank-full_parte2.csv')

## Fim da Parte 2