![title](imagens/cabec_09b.jpg)

## Transformação e Codificação de Variáveis...
## Mini-Projeto 9 - Label Encoding

A preparação dos dados é uma etapa crucial. Em meio a esse vasto campo de análise e adequação dos dados, uma das tarefas fundamentais é entender e transformar as variáveis presentes nos conjuntos de dados. Através de uma sequência didática cuidadosamente elaborada, podemos explorar esse processo de transformação, capacitando-nos para lidar com variáveis de diferentes naturezas de forma eficiente.

Através da importação do módulo "datetime", objetivamos focar na manipulação de datas e horários, essenciais em muitos conjuntos de dados do mundo real. Utilizando a data atual como ponto de partida, criamos uma lista contendo as datas dos últimos 30 dias, uma representação prática e relevante para muitos cenários de análise temporal.

Em seguida, transformamos essa lista em um DataFrame, estrutura de dados tabular, e adicionamos uma coluna indicando o dia da semana correspondente a cada data. Essa etapa não apenas enriquece nosso conjunto de dados com informações contextuais, mas também nos familiariza com as funcionalidades de manipulação de datas do Pandas.

Para melhorar a utilidade dessa informação, realizamos uma codificação dos dias da semana, convertendo seus nomes em números correspondentes. Esse processo, conhecido como **"label encoding"**, é uma técnica comum para lidar com variáveis categóricas em conjuntos de dados, tornando-as compatíveis com algoritmos de Machine Learning que requerem entradas numéricas.

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python usada neste Projeto no Jupyter Notebook:', python_version())

Versão da Linguagem Python usada neste Projeto no Jupyter Notebook: 3.11.7

In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote
# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada
# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [3]:
# Vamos trabalhar com o Pandas... e vamos importar o pacote para manipulação de data e hora (datetime)
import pandas as pd
import datetime

In [4]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "pyPRO - Seja um Profissional Python!" --iversions

Author: pyPRO - Seja um Profissional Python!

pandas: 2.2.2

In [5]:
# Extrai a data atual do sistema
data_atual = datetime.datetime.now()

In [6]:
data_atual

datetime.datetime(2024, 5, 14, 9, 38, 31, 496145)

In [7]:
# Vamos gerar uma lista com a data dos 30 dias anteriores à data atual
lista_datas = [data_atual - datetime.timedelta(days = d) for d in range(0,30) ]

In [8]:
lista_datas

[datetime.datetime(2024, 5, 14, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 13, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 12, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 11, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 10, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 9, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 8, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 7, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 6, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 5, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 4, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 3, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 2, 9, 38, 31, 496145),
 datetime.datetime(2024, 5, 1, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 30, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 29, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 28, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 27, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 26, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 25, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 24, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 23, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 22, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 21, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 20, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 19, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 18, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 17, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 16, 9, 38, 31, 496145),
 datetime.datetime(2024, 4, 15, 9, 38, 31, 496145)]

In [9]:
# Vamos colocar agora essa lista em um DataFrame
df = pd.DataFrame(lista_datas)

In [10]:
df.head()

                           0
0 2024-05-14 09:38:31.496145
1 2024-05-13 09:38:31.496145
2 2024-05-12 09:38:31.496145
3 2024-05-11 09:38:31.496145
4 2024-05-10 09:38:31.496145

In [11]:
# Vamos adequar o nome da coluna
df.columns = ['Data']

In [12]:
df.head()

                        Data
0 2024-05-14 09:38:31.496145
1 2024-05-13 09:38:31.496145
2 2024-05-12 09:38:31.496145
3 2024-05-11 09:38:31.496145
4 2024-05-10 09:38:31.496145

In [13]:
# VAmos criar mais uma coluna no dataframe, com o nome do dia da semana, de cada uma das datas.
df['Dia_da_Semana'] = df['Data'].dt.day_name()

In [14]:
df

                         Data Dia_da_Semana
0  2024-05-14 09:38:31.496145       Tuesday
1  2024-05-13 09:38:31.496145        Monday
2  2024-05-12 09:38:31.496145        Sunday
3  2024-05-11 09:38:31.496145      Saturday
4  2024-05-10 09:38:31.496145        Friday
5  2024-05-09 09:38:31.496145      Thursday
6  2024-05-08 09:38:31.496145     Wednesday
7  2024-05-07 09:38:31.496145       Tuesday
8  2024-05-06 09:38:31.496145        Monday
9  2024-05-05 09:38:31.496145        Sunday
10 2024-05-04 09:38:31.496145      Saturday
11 2024-05-03 09:38:31.496145        Friday
12 2024-05-02 09:38:31.496145      Thursday
13 2024-05-01 09:38:31.496145     Wednesday
14 2024-04-30 09:38:31.496145       Tuesday
15 2024-04-29 09:38:31.496145        Monday
16 2024-04-28 09:38:31.496145        Sunday
17 2024-04-27 09:38:31.496145      Saturday
18 2024-04-26 09:38:31.496145        Friday
19 2024-04-25 09:38:31.496145      Thursday
20 2024-04-24 09:38:31.496145     Wednesday
21 2024-04-23 09:38:31.496145       Tuesday
22 2024-04-22 09:38:31.496145        Monday
23 2024-04-21 09:38:31.496145        Sunday
24 2024-04-20 09:38:31.496145      Saturday
25 2024-04-19 09:38:31.496145        Friday
26 2024-04-18 09:38:31.496145      Thursday
27 2024-04-17 09:38:31.496145     Wednesday
28 2024-04-16 09:38:31.496145       Tuesday
29 2024-04-15 09:38:31.496145        Monday

### Label Encoding

In [15]:
# Criamos um dicionário mapeando dia da semana com um número correspondente
# Obs: se o seu sistema estiver em português e se for necessário, use os dias da semana em português
dic_dia_semana = {'Monday':1, 
                   "Tuesday":2,
                   "Wednesday":3,
                   "Thursday":4,
                   "Friday":5,
                   "Saturday":6,
                   "Sunday":7}

In [16]:
# AGORA CHEGAMOS AO PONTO.... FAZER O ENCODING --> label Encoding
# Vamos substituir o nome da semana pelo número correspondente
df['Codigo_Dia_Semana'] = df['Dia_da_Semana'].map(dic_dia_semana)

In [17]:
df

                         Data Dia_da_Semana  Codigo_Dia_Semana
0  2024-05-14 09:38:31.496145       Tuesday                  2
1  2024-05-13 09:38:31.496145        Monday                  1
2  2024-05-12 09:38:31.496145        Sunday                  7
3  2024-05-11 09:38:31.496145      Saturday                  6
4  2024-05-10 09:38:31.496145        Friday                  5
5  2024-05-09 09:38:31.496145      Thursday                  4
6  2024-05-08 09:38:31.496145     Wednesday                  3
7  2024-05-07 09:38:31.496145       Tuesday                  2
8  2024-05-06 09:38:31.496145        Monday                  1
9  2024-05-05 09:38:31.496145        Sunday                  7
10 2024-05-04 09:38:31.496145      Saturday                  6
11 2024-05-03 09:38:31.496145        Friday                  5
12 2024-05-02 09:38:31.496145      Thursday                  4
13 2024-05-01 09:38:31.496145     Wednesday                  3
14 2024-04-30 09:38:31.496145       Tuesday                  2
15 2024-04-29 09:38:31.496145        Monday                  1
16 2024-04-28 09:38:31.496145        Sunday                  7
17 2024-04-27 09:38:31.496145      Saturday                  6
18 2024-04-26 09:38:31.496145        Friday                  5
19 2024-04-25 09:38:31.496145      Thursday                  4
20 2024-04-24 09:38:31.496145     Wednesday                  3
21 2024-04-23 09:38:31.496145       Tuesday                  2
22 2024-04-22 09:38:31.496145        Monday                  1
23 2024-04-21 09:38:31.496145        Sunday                  7
24 2024-04-20 09:38:31.496145      Saturday                  6
25 2024-04-19 09:38:31.496145        Friday                  5
26 2024-04-18 09:38:31.496145      Thursday                  4
27 2024-04-17 09:38:31.496145     Wednesday                  3
28 2024-04-16 09:38:31.496145       Tuesday                  2
29 2024-04-15 09:38:31.496145        Monday                  1

## Fim do Mini-Projeto 9